version: "3.9"
services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes: 
      - ./data:/app/data
    command: ["npx", "next", "start"]
